baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = true 
    respectDoNotTrack = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youTube]
    disable = false
    privacyEnhanced = false
[services]
  [services.googleAnalytics]
    ID = 'G-0ECG4GCCN5'
