baseURL = 'https://example.org/'
languageCode = 'en-us'
title =  "Anderson Kao's Blog"
theme = 'ananke'
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    disable = true 
    respectDoNotTrack = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youTube]
    disable = false
    privacyEnhanced = false
